config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  # devise_for :users
  # resources :roles, path: 'indexr'
  
  # resources :user, path: 'indexur' do
  #   member do
  #     get :confirm_email
  #   end
  # end

  # resources :hotels, path: 'indexh'
  # resources :menus_roles, path: 'indexmr'
  # resources :packages, path: 'indexp'
  # resources :hotels_users, path: 'indexhu'

  # # root 'roles#index'
  # # get 'roles/index'

  # # resources :films
  # # root 'films#index'
  # # resources :bases, path: 'i'
  # get '/bases/hotelList'
  # get '/bases/super'
  # get '/bases/superhome'
  # get '/bases/user'
  # get '/bases/userhome'
  # root 'bases#indux'
  # # get 'roles/index'
  # # get 'roles/new'
  
  # # get 'packages/indux'
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  ###########################################################################################
#   namespace :v1 do
#     resources :hotels, only: [:index, :show] do 
#       collection {
#         resources :access
#       }
#       resources :roles
#       resources :users
#     end

#     resources :dashboards, only: :index do 
#       collection {
#         get :home
#       }
#     end
#   end


#   root 'v1/dashboards#index'
# end

##################### V2
# devise_for :users, except: :create
# devise_for :users, :controllers => {:registrations => "registrations"}, skip: [:sessions, :registrations, :passwords]
resources :articles
resources :webreqs
devise_for :users, :controllers => {:registrations => "registrations"}
devise_scope :user do
  get    '/v2/hotels/:hotel_id/users/sign_up', to: 'registrations#new',    as: :newz_user_registration
end
# get 'users/sign_up' => '/v2/hotels/:hotel_id/users'
# get '/v2/hotels/:hotel_id/users/sign_up', to: 'registration#new'
namespace :v2 do
  resources :excels do
      collection { post :import }
  end
  resources :hotels, only: [:index, :show] do 
    # collection {
    #   resources :access
    # }
    resources :roles do
      resources :menus_roles
    end
    
    resources :users do
      # devise_for :users, :controllers => {:registrations => "registrations"}
    end
    # get "/v2/hotels/:hotel_id/cusers/new" => "devise/registrations#new", as: "new_v2_hotel_cuser"
    # post 'v2_hotel_cusers' => 'users#create', as: :v2_hotel_cusers     
  end
  resources :chotels
  resources :packages
  resources :menus
  resources :hotels_users
  resources :dashboards, only: :index do 
    collection {
      get :home
    }

  end
end


root 'v2/dashboards#index'

end

app/models/webreq.rb
class Webreq < ApplicationRecord
    def content_length
        # uri = URI.parse(url)
        # response = Net::HTTP.start(uri.host, uri.port) { |http| http.request_head(uri.path) }
        # response["content-length"].to_i
        0
    end
end

app/controllers/webreqs_controller.rb
class WebreqsController < ApplicationController
    def index
        # @webreqs = Webreq.all
        @webreqs = Webreq.all
        # same as first line but sort in descending (DESC) order 
        # based on what time they were created
      end
    
      def new
          @webreq = Webreq.new
      end
    
    
      def create
        @webreq = Webreq.new(webreq_params)
        if @webreq.save
          redirect_to @webreq
        else
          render 'new'
        end
      end
    
      def show
        @webreq = Webreq.find(params[:id])
      end
    
      def edit
        @webreq = Webreq.find(params[:id])
      end
    
      def update
        @webreq = Webreq.find(params[:id])
        if @webreq.update(webreq_params)
          redirect_to @webreq
        else
          render 'edit'
        end
      end
    
      def destroy
        @webreq = Webreq.find(params[:id])
        @webreq.destroy
        redirect_to root_path
      end
    
      private
    
      def webreq_params
          # require the :webreq table
          # security mesure called 'strong params' where we must permit
          # the different attributes (:title, :description) that you 
          # want to allow to be written to our database
          params.require(:webreq).permit(:url);
      end
end

app/helpers/webreqs_helper.rb
module WebreqsHelper
end

app/views/webreqs/_filmform.html.erb
<%
  # form_for is a rails helper for rendering forms in the view  
  # @film is an instance scoped variable that is declared in 
  # films_controller new method. It points to a new
  # instance of the Film model
  # f.submit will need a create action
%>


<%= form_for @webreq do |f| %>
  <%= f.label :url %><br>
  <%= f.text_field :url %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/webreqs/edit.html.erb
<h3>Edit Page</h3>

<% # pulls in a partial from _form.html.erb %>
<%= render 'filmform' %>

app/views/webreqs/index.html.erb
<h3>Listings Page</h3>



<%
  # this is called by the index method in 
  # the webreqs controller
%>


<h3>webreqs Home Page</h3>
<%= link_to "Home", root_path %>
<br/>
<%= link_to "Add New webreq", new_webreq_path %>


<% @webreqs.each do |webreq| %>
  <h3><%= webreq.url %></h3>
  <br>
  <%= link_to "Read More", webreq %>
<% end %>

app/views/webreqs/new.html.erb
<h3>Add New Webreq Page</h3>

<% # pulls in a partial from _form.html.erb %>
<%= render 'filmform' %>

app/views/webreqs/show.html.erb
<h3>Show Webreq Page</h3>

<h3><%= @webreq.url %></h3>
<%= link_to "Edit Webreq Details", edit_webreq_path(@webreq) %>
<br/>
<%= link_to "Delete Webreq", webreq_path(@webreq), method: :delete, data: {confirm: "Are you sure?"} %>

<p>
  <strong>URL:</strong>
  <%= @webreq.url %>
</p>

<p>
  <strong>File Size:</strong>
  <%= number_to_human_size(@webreq.content_length) %>
</p>